name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0-dev.1588+2111f4c38

      - name: Build and test
        run: zig build test

